Pandas Tutorial

Data frame : Special object to put data in tabular form

Installation

In [1]:
!pip install pandas

In [2]:
import numpy as np 
import pandas as pd

In [3]:
# Creating a dataframe
user_data = { 
"Marks A" : np.random.randint(1,100,5),
"Marks B" : np.random.randint(50,100,5),
"Marks C" : np.random.randint(20,100,5)
            }
print(user_data)

{'Marks A': array([ 5, 76, 68, 49, 67]), 'Marks B': array([56, 65, 78, 95, 80]), 'Marks C': array([20, 38, 90, 29, 26])}


In [4]:
df = pd.DataFrame(user_data)
print(df)

   Marks A  Marks B  Marks C
0        5       56       20
1       76       65       38
2       68       78       90
3       49       95       29
4       67       80       26


In [5]:
df.head(n=3)

Marks A  Marks B  Marks C
0        5       56       20
1       76       65       38
2       68       78       90

In [6]:
print(df.columns)

Index(['Marks A', 'Marks B', 'Marks C'], dtype='object')


In [7]:
df.to_csv('marks.csv')

In [8]:
mydata = pd.read_csv('marks.csv')

In [9]:
print(mydata)

   Unnamed: 0  Marks A  Marks B  Marks C
0           0        5       56       20
1           1       76       65       38
2           2       68       78       90
3           3       49       95       29
4           4       67       80       26


In [10]:
 mydata = mydata.drop(columns =["Unnamed: 0"])

In [11]:
print(mydata)

   Marks A  Marks B  Marks C
0        5       56       20
1       76       65       38
2       68       78       90
3       49       95       29
4       67       80       26


In [17]:
#selecting row from a dataframe

df.iloc[3]

Marks A    49
Marks B    95
Marks C    29
Name: 3, dtype: int32

In [23]:
# selecting row and column from dataframe
df.iloc[3,1]

95

In [24]:
df.iloc[2][1]

78

In [29]:
#Getting the index of particular column

index= df.columns.get_loc("Marks B")
print(index)

1


In [31]:
# finding the data with the help of index

df.iloc[3,index]

95

In [32]:
#getting index of two columns together

idx = [df.columns.get_loc("Marks B"),df.columns.get_loc("Marks C")]

print(idx)

[1, 2]


In [34]:
#getting two columns
df.iloc[4,idx]

Marks B    80
Marks C    26
Name: 4, dtype: int32

In [39]:
df.iloc[0:4,idx] #or df.iloc[:4,idx]

Marks B  Marks C
0       56       20
1       65       38
2       78       90
3       95       29

In [45]:
# selecting first three rows and column 1 and 2(not column 0)

df.iloc[:3,[1,2]]

Marks B  Marks C
0       56       20
1       65       38
2       78       90

In [46]:
# Sorting the dataframe
mydata

Marks A  Marks B  Marks C
0        5       56       20
1       76       65       38
2       68       78       90
3       49       95       29
4       67       80       26

In [49]:
# Sorting the dataframe in ascending order for Marks A
mydata.sort_values(by=["Marks A"], ascending= True)

Marks A  Marks B  Marks C
0        5       56       20
3       49       95       29
4       67       80       26
2       68       78       90
1       76       65       38

In [50]:
data_array =mydata.values
print(type(mydata))

<class 'pandas.core.frame.DataFrame'>


In [51]:
#getting the shape of data
mydata.shape

(5, 3)

In [54]:
print(data_array)

[[ 5 56 20]
 [76 65 38]
 [68 78 90]
 [49 95 29]
 [67 80 26]]


In [62]:
#Converting Numpy array back to dataframe
new_df = pd.DataFrame(data_array, dtype="int32", columns= ["physics", "Chemistry","Maths"])

print(new_df)

   physics  Chemistry  Maths
0        5         56     20
1       76         65     38
2       68         78     90
3       49         95     29
4       67         80     26


In [69]:
# Converting DataFrame to CSV
new_df.to_csv("PCM.csv", index =False)

In [68]:
pcm = pd.read_csv("PCM.csv")

In [70]:
print(pcm)

   physics  Chemistry  Maths
0        5         56     20
1       76         65     38
2       68         78     90
3       49         95     29
4       67         80     26
